
VERSION = "v1"
TYPE_DEVICES = "devices"

BASE_V1_DEVICE = f"{VERSION}/{TYPE_DEVICES}"

# GENERAL
STATUS_TOPIC = "status"

# DEVICE
UPLINK_TOPIC = f"{BASE_V1_DEVICE}/uplink-p2p"
DOWNLINK_TOPIC = f"{BASE_V1_DEVICE}/downlink-p2p"